### ISSUE TITLE
start trip Location Permission 

### ISSUE THREAD

**Issue by ToqaEid** [mikeAttia/tripz#14]
location permission doesn't appear before opening google 
so if the location is not opened google maps can't find the route and after the user go back frim the maps to our app location permission will appear and if the user accepted the permission it opens google maps again

so we need to show the location permission before going to google maps and lock opening the maps if there's no location permission 

@mhmdrmdn94

**Comment by mo-abdelhafez** [comment]
Ok, I am working on it NOW
